### PR TITLE
Add github ci/cd, Update dockerfile

### PR DESCRIPTION
**Pull request by luigi311**
Add github action job, this will build the deploy folder and upload it as an artifact so people can download it from here without needing to setup a development environment if they want to build their own docker image.

Docker
- Update dockerfile to use newer base image
- Add support for building different architectures but only amd64 is support
- Use single docker image for both server and node

With the server and node now being combined into a single image you will need to change how you launch the docker command. Everything is exactly the same except you will now add --server or --node at the end of the command for what you need.

ex for server
docker run revenz/fileflows:latest --server

ex for node
docker run revenz/fileflows:latest --node

The unraid templates will need to be updated as well. They should now both point to the same image and you will need to add --node or --server to the post arguments.

To get the CD working you will need to go to the repository settings > Secrets > Actions and create one called DOCKER_USERNAME with your dockerhub username so revenz and another one DOCKER_TOKEN with a token you generate from docker hub. Once those are in whenever you push something it will create the docker container and push it to dockerhub automatically.

## CLA

[X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the FileFlows project and the project owner. My contribution will become licensed under the same license as the overall project.

### CODE REVIEW

**Comment by revenz** [comment]
To summarize these are the changes?
1. Update dockerfile to use official ubuntu base image
2. Add support for building different architectures but only amd64 is support
3. Use single docker image for both server and node

?

If so, 
1. what's the benefit of that image vs the one I'm currently using?
2. doesn't really change anything from now correct?
3. single docker I do like, makes deployment slightly faster.   

Regarding the github action, I would rather keep the prebuilt binaries through the fileflows.com website.  I have finer control over the build process and it then uses the same built binaries used on Windows and the docker images.

**Comment by luigi311** [comment]
1. Correct except im not going with the official base image anymore, i left it using the linuxserver base image but updated to a newer release. It looks like they are using the official ubuntu image but adding in s6 so i dont see a need to move away from it. Benefit being that all the base applications are now updated to a new version, nothing really major but figured i would make the change now while im changing everything.
2. Correct nothing changes, the normal build should still act exactly the same and is still targeted towards amd64.
3. Agreed, you no longer have to upload two individual images anymore

The github action by default will not upload anything to dockerhub or anywhere. It will compile everything and store it on the action page as an artifact for troubleshooting or development purposes for a limited time. This will allow for validation on PR and commits to make sure its not breaking anything as it will go through the compile process and allow you to see on the PR quickly if it will break anything. You will still handle all the releases manually with your current workflow including uploading to dockerhub. If in the future you ever do decide to migrate to the github action for uploading to dockerhub automatically you just need to set the secret variables and it will automatically start pushing up. 

As for pushing to dockerhub i would also recommend you to start tagging your releases along side pushing to latest as well. Instead of just push latest also push to tag  0.5.0.684 as an example. Allows people to easily revert if a breaking change happens.

**Comment by revenz** [comment]
my concern with the github action is it will produce artifacts for users to download from here, and some people may download those binaries instead of the official ones and cause confusion.  Or am I missing something and they wont be able to be downloaded?

Can you update the entry points so if no parameter is given it defaults to running the server?

**Comment by revenz** [comment]
I've taken most of this and created a new Dockerfile.   I had to modify it a little for the actual deployment, but the bulk is the same.

**Pull request closed without merging**
